name: Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '37 6 * * 1' # monday at 6:37 UTC

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
      fail-fast: false

    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: vendor/bin/tester tests -s -C

  static_analysis:
    name: PHPStan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: vendor/bin/phpstan --no-progress

  lowest_dependencies:
    name: Lowest Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - run: composer update --no-interaction --no-progress --prefer-dist --prefer-lowest --prefer-stable
      - run: vendor/bin/tester tests -s -C
